### ISSUE TITLE
error for "go get github.com/xuqingfeng/fregata/cmd/fregatad"

### ISSUE THREAD

**Issue by mondface** [xuqingfeng/fregata#1]
hallo,
i have these errors for:
"go get github.com/xuqingfeng/fregata/cmd/fregatad"

github.com/gorilla/mux
.go/src/github.com/gorilla/mux/mux.go:122: req.URL.EscapedPath undefined (type *url.URL has no field or method EscapedPath)
.go/src/github.com/gorilla/mux/regexp.go:171: req.URL.EscapedPath undefined (type *url.URL has no field or method EscapedPath)
.go/src/github.com/gorilla/mux/regexp.go:281: req.URL.EscapedPath undefined (type *url.URL has no field or method EscapedPath)

regards
frAnk

**Comment by xuqingfeng** [comment]
Hi @mondface, I can't reproduce it with `go1.8.1 linux/arm`.

If you are using go older than 1.8, you need to specify `GOPATH`.
