### ISSUE TITLE
Any plans for support of further protocols?

### ISSUE THREAD

**Issue by hblaschka** [xuqingfeng/fregata#3]
Hi xuqingfeng,

any plans for the support of further protocols (e.g. additional IM systems like Facebook Chat, etc.) in the future? We packaged Fregata (in an a small community driven open source project) to enable the users of a German Smart Home Gateway w/o support for Mail (yet) to send out mails using the REST API  provided with the system and were asked if more is coming...

**Comment by xuqingfeng** [comment]
I will definitely add more services in the future.

Personally, I don't use Facebook Chat, not sure how much work it will take.

PR is welcome 😄
